function roomsim_info
% Usage:  roomsim_info;  Information about Roomsim
%---------------------------------------------------------------------------
% Copyright (C) 2003  Douglas R Campbell
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 2
% of the License, or (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program in the MATLAB file roomsim_licence.m ; if not,
%  write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
%----------------------------------------------------------------------------- 
% Functions called:

about_roomsim=strvcat(...
     'Roomsim is a MATLAB implementation of a mirror image model of the reverberation'...
    ,'experienced at a receiver (mono sensor, two sensors or two ears of a head) in a'...
    ,'"shoebox" room. It incorporates frequency dependent absorption at the reflective'...
    ,'surfaces and in the airspace of the room.' ...
    ,'   The simulation of the head utilises Head Related Transfer Functions (HRTF),'...
    ,'actually Head Related Impulse Responses (HRIR), provided from measurements made'...
    ,'on a Kemar mannequin at MIT (http://xenia.media.mit.edu/~kdm/hrtf.html ,Apr 2003)'...
    ,'or on real subjects and a Kemar at University of California, Davis '...
    ,'(http://interface.cipic.ucdavis.edu ,Apr 2003).'...
    ,'Parameter values are acquired either from a *.mat file saved from a previous session,'...
    ,'an Excel spreadsheet, a Text file, or by prompted manual input.' ...
    ,'setup_TEST.mat is supplied for an initial check that the installation is successful.'...
    ,'Example Excel and Text files are supplied for the user to copy and modify. '...
    ,'   Roomsim is derived from the image method software as described by Allen and Berkley '...
    ,'(1979). The core of the original version of this MATLAB m-code implementation was '...
    ,'written by Kalle J. Palomaki (Helsinki University of Technology, Finland) and colleagues '... 
    ,'at Sheffield University. Their code was reorganised and extended to this menu driven version '...
    ,'by Douglas R. Campbell (University of Paisley, Scotland, UK) during Sept2002/April 2003.'...
    ,'---------------------------------------------------------------------------'...
    ,'Acknowledgements: The authors acknowledge support from the following organisations:'...
    ,'D.R. Campbell; Defeating Deafness (246:PAI:DC). '...
    ,'K. Palomaki; EC TMR SPHEAR, The Academy of Finland, and Finnish Tekniikan edistamissaatio.'...
    ,'---------------------------------------------------------------------------'...
    ,'References for image method program code,'...
    ,'environmental acoustic data, and acoustic simulation issues:'...
    ,'J B Allen and D A Berkley, "Image method for efficiently simulating small-room acoustics",'...
    ,'JASA 65(4), 1979, 943-950. (A6) '...
    ,'F. Alton Everest, "The Master Handbook of Acoustics", McGraw-Hill, 4th Ed, 2001. (A2) '...
    ,'D. E. Hall, "Musical Acoustics", 2nd Ed, Brooks/Cole Publishing, 1991. (A1) '...
    ,'Tapio Lokki (2002), "Physically-based auralization" PhD Thesis,'...
    ,'Helsinki Univ. of Technology. Publications in Telecommunications Software and Multimedia.'...
    ,'P M Peterson, "Simulating the response of multiple microphones to a '...
    ,'  single acoustic source in a reverberant room", JASA 80(5),1986, 1527-1529. (A5) '...
    ,'B J Smith, R J Peters, S Owen, "Acoustics and noise control", '...
    ,'  Adison Wesley Longman, 2nd Ed. 1998. (A4) '...
    ,'http://hyperphysics.phy-astr.gsu.edu/hbase/acoustic/revmod.html#c4 (Nov 2002) (A3) '...
    ,'(http://interface.cipic.ucdavis.edu ,Apr 2003)'...
    ,'(http://xenia.media.mit.edu/~kdm/hrtf.html ,Apr 2003)'...
    ,'----------------------------------------------------------------------------');

%--------------------------------------------------------------------------
listdlg('PromptString','About Roomsim','SelectionMode','single','ListSize',[600 500],'ListString',about_roomsim,'Name','roomsim_info');
beep;
%------------------ End of roomsim_info.m ----------------------------------
